name: 搜索结果发现

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟
  workflow_dispatch:
    inputs: {}

jobs:
  search:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 搜索并更新房间
        run: python searcher.py
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOUYIN_COOKIE: ${{ secrets.DOUYIN_COOKIE }}
